FROM alpine:3.21 AS builder
RUN apk add --no-cache bash git g++ make sqlite-dev zlib-dev
RUN git clone --depth=1 https://github.com/felt/tippecanoe.git /src
WORKDIR /src
RUN make -j$(nproc) && make install

FROM alpine:3.21
RUN apk add --no-cache libstdc++ sqlite-libs zlib
COPY --from=builder /usr/local/bin/tippecanoe /usr/local/bin/tippecanoe
COPY --from=builder /usr/local/bin/tile-join /usr/local/bin/tile-join
ENTRYPOINT ["tippecanoe"]
